fdjac1 – minpack
fdjac1 Subroutine
55 statements
Source File
public subroutine fdjac1(fcn, n, x, Fvec, Fjac, Ldfjac, Iflag, Ml, Mu, Epsfcn, Wa1, Wa2)
this subroutine computes a forward-difference approximation to the n by n jacobian matrix associated with a specified problem of n functions in n variables. if the jacobian has a banded form, then function evaluations are saved by only approximating the nonzero terms.
Arguments
Type Intent Optional Attributes Name
procedure(func) :: fcn
the user-supplied subroutine which calculates the functions.
integer, intent(in) :: n
a positive integer input variable set to the number of functions and variables.
real(kind=wp), intent(inout) :: x(n)
an input array of length n.
real(kind=wp), intent(in) :: Fvec(n)
an input array of length n which must contain the functions evaluated at x.
real(kind=wp), intent(out) :: Fjac(Ldfjac,n)
an output n by n array which contains the approximation to the jacobian matrix evaluated at x.
integer, intent(in) :: Ldfjac
a positive integer input variable not less than n which specifies the leading dimension of the array fjac.
integer, intent(out) :: Iflag
an integer variable which can be used to terminate the execution of fdjac1. see description of func.
integer, intent(in) :: Ml
a nonnegative integer input variable which specifies the number of subdiagonals within the band of the jacobian matrix. if the jacobian is not banded, set ml to at least n - 1.
integer, intent(in) :: Mu
a nonnegative integer input variable which specifies the number of superdiagonals within the band of the jacobian matrix. if the jacobian is not banded, set mu to at least n - 1.
real(kind=wp), intent(in) :: Epsfcn
an input variable used in determining a suitable step length for the forward-difference approximation. this approximation assumes that the relative errors in the functions are of the order of epsfcn. if epsfcn is less than the machine precision, it is assumed that the relative errors in the functions are of the order of the machine precision.
real(kind=wp), intent(inout) :: Wa1(n)
work array of length n.
real(kind=wp), intent(inout) :: Wa2(n)
work array of length n. if ml + mu + 1 is at least n, then the jacobian is considered dense, and wa2 is not referenced.
Called by
Contents
Variables
i j k msum eps h temp
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
integer, public :: k
integer, public :: msum
real(kind=wp), public :: eps
real(kind=wp), public :: h
real(kind=wp), public :: temp
Call graph
hybrd calls fdjac1
minpack_hybrd calls hybrd
hybrd1 calls hybrd
minpack_hybrd1 calls hybrd1