lmder1 – minpack
lmder1 Subroutine
22 statements
Source File
public subroutine lmder1(fcn, m, n, x, Fvec, Fjac, Ldfjac, Tol, Info, Ipvt, Wa, Lwa)
Arguments
Type Intent Optional Attributes Name
real :: fcn
integer :: m
integer :: n
double precision :: x(n)
double precision :: Fvec(m)
double precision :: Fjac(Ldfjac,n)
integer :: Ldfjac
double precision :: Tol
integer :: Info
integer :: Ipvt(n)
double precision :: Wa(Lwa)
integer :: Lwa
Calls
Contents
None
Call graph
lmder1 calls lmder
lmder calls dpmpar, qrfac, enorm
qrfac calls dpmpar, enorm