lmdif1 – minpack
lmdif1 Subroutine
29 statements
Source File
public subroutine lmdif1(fcn, m, n, x, Fvec, Tol, Info, Iwa, Wa, Lwa)
the purpose of lmdif1 is to minimize the sum of the squares of m nonlinear functions in n variables by a modification of the levenberg-marquardt algorithm. this is done by using the more general least-squares solver lmdif. the user must provide a subroutine which calculates the functions. the jacobian is then calculated by a forward-difference approximation.
Arguments
Type Intent Optional Attributes Name
procedure(func2) :: fcn
the user-supplied subroutine which calculates the functions.
integer, intent(in) :: m
a positive integer input variable set to the number of functions.
integer, intent(in) :: n
a positive integer input variable set to the number of variables. n must not exceed m.
real(kind=wp), intent(inout) :: x(n)
an array of length n. on input x must contain an initial estimate of the solution vector. on output x contains the final estimate of the solution vector.
real(kind=wp), intent(out) :: Fvec(m)
an output array of length m which contains the functions evaluated at the output x.
real(kind=wp), intent(in) :: Tol
a nonnegative input variable. termination occurs when the algorithm estimates either that the relative error in the sum of squares is at most tol or that the relative error between x and the solution is at most tol.
integer, intent(out) :: Info
an integer output variable. if the user has terminated execution, info is set to the (negative) value of iflag. see description of fcn. otherwise, info is set as follows:
info = 0 improper input parameters.
info = 1 algorithm estimates that the relative error in the sum of squares is at most tol.
info = 2 algorithm estimates that the relative error between x and the solution is at most tol.
info = 3 conditions for info = 1 and info = 2 both hold.
info = 4 fvec is orthogonal to the columns of the jacobian to machine precision.
info = 5 number of calls to fcn has reached or exceeded 200*(n+1).
info = 6 tol is too small. no further reduction in the sum of squares is possible.
info = 7 tol is too small. no further improvement in the approximate solution x is possible.
integer, intent(inout) :: Iwa(n)
an integer work array of length n.
real(kind=wp), intent(inout) :: Wa(Lwa)
a work array of length lwa.
integer, intent(in) :: Lwa
a positive integer input variable not less than mn+5n+m.
Calls
Called by
Contents
Variables
maxfev mode mp5n nfev nprint epsfcn ftol gtol xtol factor
Variables
Type Visibility Attributes Name Initial
integer, public :: maxfev
integer, public :: mode
integer, public :: mp5n
integer, public :: nfev
integer, public :: nprint
real(kind=wp), public :: epsfcn
real(kind=wp), public :: ftol
real(kind=wp), public :: gtol
real(kind=wp), public :: xtol
real(kind=wp), public, parameter :: factor = 1.0e2_wp
Call graph
lmdif1 calls lmdif
lmdif calls qrfac, fdjac2, enorm
qrfac calls enorm
minpack_lmdif1 calls lmdif1