minpack_lmstr1 – minpack
minpack_lmstr1 Subroutine
26 statements
Source File
private subroutine minpack_lmstr1(fcn, m, n, x, fvec, fjac, ldfjac, tol, info, ipvt, wa, lwa, udata) bind(c)
Arguments
Type Intent Optional Attributes Name
procedure(minpack_fcn_lmstr) :: fcn
integer(kind=c_int), value :: m
integer(kind=c_int), value :: n
real(kind=c_double), intent(inout) :: x(n)
real(kind=c_double), intent(out) :: fvec(m)
real(kind=c_double), intent(out) :: fjac(ldfjac,n)
integer(kind=c_int), value :: ldfjac
real(kind=c_double), value :: tol
integer(kind=c_int), intent(out) :: info
integer(kind=c_int), intent(out) :: ipvt(n)
real(kind=c_double), intent(inout) :: wa(lwa)
integer(kind=c_int), value :: lwa
type(c_ptr), value :: udata
Calls
Contents
Source Code
minpack_lmstr1
Source Code
    subroutine minpack_lmstr1(fcn, m, n, x, fvec, fjac, ldfjac, tol, info, ipvt, wa, lwa, &
            & udata) &
            & bind(c)
        procedure(minpack_fcn_lmstr) :: fcn
        integer(c_int), value :: m
        integer(c_int), value :: n
        integer(c_int), value :: ldfjac
        integer(c_int), intent(out) :: info
        integer(c_int), value :: lwa
        integer(c_int), intent(out) :: ipvt(n)
        real(c_double), value :: tol
        real(c_double), intent(inout) :: x(n)
        real(c_double), intent(out) :: fvec(m)
        real(c_double), intent(out) :: fjac(ldfjac, n)
        real(c_double), intent(inout) :: wa(lwa)
        type(c_ptr), value :: udata
        call lmstr1(wrap_fcn, m, n, x, fvec, fjac, ldfjac, tol, info, ipvt, wa, lwa)
    contains
        subroutine wrap_fcn(m, n, x, fvec, fjrow, iflag)
            integer, intent(in) :: m
            integer, intent(in) :: n
            integer, intent(inout) :: iflag
            real(wp), intent(in) :: x(n)
            real(wp), intent(inout) :: fvec(m)
            real(wp), intent(inout) :: fjrow(n)
            call fcn(m, n, x, fvec, fjrow, iflag, udata)
        end subroutine wrap_fcn
    end subroutine minpack_lmstr1
Call graph
minpack_lmstr1 calls lmstr1
lmstr1 calls lmstr
lmstr calls enorm, rwupdt, qrfac
qrfac calls enorm