minpack_hybrd1 – minpack
minpack_hybrd1 Subroutine
20 statements
Source File
public subroutine minpack_hybrd1(fcn, n, x, fvec, tol, info, Wa, Lwa, udata) bind(c)
Arguments
Type Intent Optional Attributes Name
procedure(minpack_func) :: fcn
integer(kind=c_int), value :: n
real(kind=c_double), intent(inout) :: x(n)
real(kind=c_double), intent(out) :: fvec(n)
real(kind=c_double), value :: tol
integer(kind=c_int), intent(out) :: info
real(kind=c_double), intent(inout) :: Wa(Lwa)
integer(kind=c_int), value :: Lwa
type(c_ptr), value :: udata
Calls
Contents
Subroutines
wrap_fcn
Subroutines
subroutine wrap_fcn(n, x, fvec, iflag)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(in) :: x(n)
real(kind=wp), intent(out) :: fvec(n)
integer, intent(inout) :: iflag
Call graph
minpack_hybrd1 calls hybrd1
hybrd1 calls hybrd
hybrd calls qform, qrfac, r1mpyq, enorm, r1updt, dogleg, fdjac1
qrfac calls enorm
dogleg calls enorm