qform – minpack
qform Subroutine
48 statements
Source File
public subroutine qform(m, n, q, Ldq, Wa)
this subroutine proceeds from the computed qr factorization of an m by n matrix a to accumulate the m by m orthogonal matrix q from its factored form.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: m
a positive integer input variable set to the number of rows of a and the order of q.
integer, intent(in) :: n
a positive integer input variable set to the number of columns of a.
real(kind=wp), intent(inout) :: q(Ldq,m)
an m by m array. on input the full lower trapezoid in the first min(m,n) columns of q contains the factored form. on output q has been accumulated into a square matrix.
integer, intent(in) :: Ldq
a positive integer input variable not less than m which specifies the leading dimension of the array q.
real(kind=wp), intent(inout) :: Wa(m)
a work array of length m.
Called by
Contents
Variables
i j jm1 k l minmn np1 sum temp
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
integer, public :: jm1
integer, public :: k
integer, public :: l
integer, public :: minmn
integer, public :: np1
real(kind=wp), public :: sum
real(kind=wp), public :: temp
Call graph
hybrj calls qform
hybrd calls qform
hybrd1 calls hybrd
hybrj1 calls hybrj