r1updt – minpack
r1updt Subroutine
85 statements
Source File
public subroutine r1updt(m, n, s, Ls, u, v, w, Sing)
Arguments
Type Intent Optional Attributes Name
integer :: m
integer :: n
double precision :: s(Ls)
integer :: Ls
double precision :: u(m)
double precision :: v(n)
double precision :: w(m)
logical :: Sing
Called by
Contents
None
Call graph
fdjac1 calls r1updt, fdjac1
hybrj calls r1updt
hybrj1 calls hybrj